### ISSUE TITLE
请问是否有支持android在计划？

### ISSUE THREAD

**Issue by duduathz** [zlgopen/awtk-media-player#1]
您好！
请问是否有支持android在计划？
谢谢！

**Comment by xianjimli** [comment]
* Android 移植： https://github.com/zlgopen/awtk-android
* Android 插件：https://github.com/zlgopen/awtk-mobile-plugins

**Comment by xianjimli** [comment]
目前没有。有实际的需求吗？

**Comment by duduathz** [comment]
已有解决方案，这个不需要了。谢谢！
