### ISSUE TITLE
linux_fb编译不通过，提示没有SDL2库

### ISSUE THREAD

**Issue by zhaoyangxia1990** [zlgopen/awtk-media-player#2]
awtk_linux_fb编译之后没有生成SDL2库，尝试修改scons构建文件生成SDL2库，没有成功。请协助解决

**Comment by xianjimli** [comment]
我加了SDL编译，你更新一下awtk和awtk-media-player。嵌入式版本需要自己编译alsa-lib，看下README的编译方法。

**Comment by zhaoyangxia1990** [comment]
好的，我试试，感谢！
